"""create grades tables

Revision ID: 079771977a0c
Revises: f1f1f3eff880
Create Date: 2025-06-16 11:04:04.771777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079771977a0c'
down_revision = 'f1f1f3eff880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gender_pkey'))
    )
    op.drop_table('grades')
    # ### end Alembic commands ###
