"""add grade column to enrollment

Revision ID: 826fde6fd056
Revises: 079771977a0c
Create Date: 2025-06-17 09:32:30.084706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826fde6fd056'
down_revision = '079771977a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(), nullable=True))

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
