"""ondelete constraints

Revision ID: f1f1f3eff880
Revises: 4e3545297f1b
Create Date: 2025-06-16 08:26:51.666297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f1f3eff880'
down_revision = '4e3545297f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('enrollments_student_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('enrollments_course_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('enrollments_course_id_fkey'), 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('enrollments_student_id_fkey'), 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
